### ISSUE TITLE
Invalid literal for int() with base 10: 'tings'

### ISSUE THREAD

**Issue by anjabeth** [nadbordrozd/neural_playground#1]
Hi,

I'm at the beginning stages of playing around with this (thanks for the nice utils, by the way!). I'm trying to train an LSTM on The Iliad, but when I run
```
python train_text_gen.py --train_test_path data/theiliad_cleaned.txt --model_dir models/theiliad_1 --maxlen 160 --lstm_size 128 --dropout 0.2 --batch_size 1024 --max_epochs 100 --layers 3
```
I get "Using TensorFlow backend" immediately followed by this error:

```
Traceback (most recent call last):
  File "train_text_gen.py", line 37, in <module>
    model, epoch = load_latest_model(args.model_dir)
  File "/home/anjabeth/rhymeRNN/neural_playground/utils.py", line 39, in load_latest_model
    epoch = int(path[-5:])
ValueError: invalid literal for int() with base 10: 'tings'
```

This might very well be a mistake on my end, but do you have any idea what might be going on?

**Comment by anjabeth** [comment]
Aha, fixed it, I printed out "path" since it seemed that that was what was causing the invalid int() cast, and path is models/theiliad_1/settings - I had created a text file in theiliad_1 called "settings", and that's what was messing things up. I deleted the settings file and no more error.
